config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :customers
  scope module: :customer do
    resources :customers
    resources :tweets do
      resources :tweet_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
  end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :tweet_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  attachment :tweet_image
  
  belongs_to :customer
  has_many :tweet_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end
end

app/models/tweet_comment.rb
class TweetComment < ApplicationRecord
  belongs_to :tweet
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
end

app/controllers/customer/favorites_controller.rb
class Customer::FavoritesController < ApplicationController
  def create
    tweet = Tweet.find(params[:tweet_id])
    favorite = current_customer.favorites.new(tweet_id: tweet.id)
    favorite.save
    redirect_to tweet_path(tweet)
  end

  def destroy
    tweet = Tweet.find(params[:tweet_id])
    favorite = current_customer.favorites.find_by(tweet_id: tweet.id)
    favorite.destroy
    redirect_to tweet_path(tweet)
  end
end

app/controllers/customer/tweet_comments_controller.rb
class Customer::TweetCommentsController < ApplicationController
  def create
    tweet = Tweet.find(params[:tweet_id])
    comment = current_customer.tweet_comments.new(tweet_comment_params)
    comment.tweet_id = tweet.id
    if comment.save
      redirect_to tweet_path(tweet)
    else
      redirect_to tweet_path(tweet)
    end
  end

  def destroy
    TweetComment.find_by(id: params[:id]).destroy
    redirect_to tweet_path(params[:tweet_id])
  end

  private

  def tweet_comment_params
    params.require(:tweet_comment).permit(:comment)
  end
end

app/controllers/customer/tweets_controller.rb
class Customer::TweetsController < ApplicationController
  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.customer_id = current_customer.id
    @tweet.save
    redirect_to tweets_path
  end

  def index
    @tweets = Tweet.page(params[:page]).reverse_order
  end

  def show
    @tweet = Tweet.find(params[:id])
    @tweet_comment = TweetComment.new
  end

  def destroy
  end
  
  private

  def tweet_params
    params.require(:tweet).permit(:title, :tweet_image, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/favorites_helper.rb
module Customer::FavoritesHelper
end

app/helpers/customer/tweet_comments_helper.rb
module Customer::TweetCommentsHelper
end

app/helpers/customer/tweets_helper.rb
module Customer::TweetsHelper
end

app/views/customer/tweets/index.html.erb
<% @tweets.each do |tweet| %>
  <div>
    <p>投稿ユーザー画像：</p>
    <p>タイトル：<%= tweet.title %></p>
    <p>内容：<%= tweet.body %></p>
    <p>ユーザーネーム：<%= tweet.customer.name %></p>
    <p><%= link_to "#{tweet.tweet_comments.count} コメント", tweet_path(tweet.id) %></p>
  </div>
<% end %>
<%= paginate @tweets %>

app/views/customer/tweets/new.html.erb
<h1>画像投稿フォーム</h1>
<%= form_with model: @tweet, local:true do |f| %>
  <h4>画像</h4>
  <%= f.attachment_field :tweet_image %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>内容</h4>
  <%= f.text_area :body %>
  <%= f.submit '投稿' %>
<% end %>

app/views/customer/tweets/show.html.erb
<div>

  <p>投稿ユーザー画像：</p>
  <p>タイトル：<%= @tweet.title %></p>
  <p>内容：<%= @tweet.body %></p>
  <p>ユーザーネーム：<%= @tweet.customer.name %></p>
</div>

<div>
<p>コメント件数：<%= @tweet.tweet_comments.count %></p>
<% @tweet.tweet_comments.each do |tweet_comment| %>
  <%= tweet_comment.customer.name %>
  <%= tweet_comment.created_at.strftime('%Y/%m/%d') %><%= tweet_comment.comment %>
  <% if @tweet.favorited_by?(current_customer) %>
    <p>
      <%= link_to tweet_favorites_path(@tweet), method: :delete do %>
        ♥<%= @tweet.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to tweet_favorites_path(@tweet), method: :post do %>
        ♡<%= @tweet.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>
  <% if tweet_comment.customer == current_customer %>
  <div>
    <%= link_to "削除", tweet_tweet_comment_path(tweet_comment.tweet, tweet_comment), method: :delete %>
  </div>
  <% end %>
<% end %>
</div>
<div>
<%= form_with(model:[@tweet, @tweet_comment], local: true) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
  <%= f.submit "送信する" %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Review</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if customer_signed_in? %>
      
      <li>
        <%= link_to "ログアウト", destroy_customer_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "新規登録", new_customer_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン", new_customer_session_path %>
      </li>
    <% end %>
    <%= yield %>
  </body>
</html>